
server:
  port: 9100

spring:
  application:
    name: cloud-zuul


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7901/eureka/,http://localhost:7902/eureka/,http://localhost:7903/eureka/
  instance:
    instance-id: cloud-zuul
